### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by nikkulikov** [dmitry-grasevich/tg#48]
Здравствуйте, Дмитрий!
Сразу хочу извиниться, что пишу вам в гитхаб.
Нам очень нужны php-разработчики с опытом в Magento, быть может у вас есть такой опыт?
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (именно так), если есть.

**Comment by dmitry-grasevich** [comment]
здравствуйте.
опыт есть, но работу я сейчас не ищу, спасибо.

с уважением, Дмитрий
